Header shadow and password
CPSECapstone/2.0 pull request #83
Opened 2020-05-18 01:24 UTC by ItisEeron

### Password Validator should account for Password Manager Accounts 
Now the regex used to validate passwords allows more characters. Specific special characters are permitted and should be accepted as valid passwords. Characters such as : <  or > will not be accepted as to prevent injection attacks. 

### Holding off on Header Shadow
I spent hours trying to figure this out for web. I figured out the some possible causes: Smart Components, Web Routes, withSceneHeader. However, this was taking way too much time so I decided to put this task on hold. I separated the styles into platform specific files so in the future, (probably the last sprint) maybe we can address this issue.

2020-05-20 21:14 UTC, YellowRainBoots requested changes
Service Requests on web has two navigation bars. Definitely can't stay like this
<img width="1277" alt="Screen Shot 2020-05-20 at 2 12 51 PM" src="https://user-images.githubusercontent.com/15078566/82498057-2ee07f00-9aa4-11ea-9ec3-a2f77f52015f.png">

2020-05-20 23:07 UTC, ItisEeron commented
Was that the only bug. I just ran across this in a different branch btw?

2020-05-21 00:19 UTC, YellowRainBoots commented
I haven't been able to replicate this bug on master or develop myself, so I'm wondering if it's isolated to your branch / maybe it'd be resolved if you pulled develop? I didn't test android native too much for yours because it never lowers the screen below the modal / the modal was always in the right place on develop, but I believe it was fine. I can double check though.

2020-05-21 00:21 UTC, ItisEeron commented
It's in my branch. I fixed it this morning. I was working on a one of this branch's child branch.
I just recommitted btw. Things should good.

2020-05-21 00:38 UTC, YellowRainBoots approved these changes
Approved otherwise, just two comments

2020-05-21 00:38 UTC, YellowRainBoots commented on homepairs/homepairsUI/src/modals/property-modals/EditTenantModal/EditTenantModal.tsx
> +            flex: Platform.OS === 'web' ? undefined : 1,
you used a conditional flexGrow for the appliance modal's scrollContentContainerStyle + always flex: 1 for its modalContainer, whereas for the tenant modal you made the flex for the modal Container conditional, you sure this is what you wanted?

2020-05-21 00:38 UTC, YellowRainBoots commented on homepairs/homepairsUI/src/utility/SyntaxVerification.tsx
> +    const reg = new RegExp("^([a-zA-Z0-9!@#$%^&*\-]{8,32})$");
we might need to update the error message if min password is 8 characters now

2020-05-21 00:48 UTC, YellowRainBoots approved these changes
Good comments! I'll pull the search bar stuff into a feature branch.

2020-05-21 00:55 UTC, merged